#!/usr/bin/env python3
"""Convert a ThinkCam raw-event recording -> IncEventGS dataset layout.

Target: IncEventGS (github.com/WU-CVGL/IncEventGS), pose-free 3DGS from a single
event camera. Produces the one *required* artifact -- the event array -- plus the
scaffolding the released dataloader expects.

The schema below was VERIFIED by reading IncEventGS's own loader, not the spec:

    datasets/dataset.py  get_event_chunk() ......... events[:, 2] is t
    main.py:75           accumulate_events() ........ reads [:,0]=x [:,1]=y [:,3]=p
                                                      and does out += (p + polarity_offset)
    configs/.../simu_event.yaml ..................... polarity_offset: 0.0
    main.py:384          self.events.astype(np.float32)  (loader downcasts to f32)

Consequences, baked in as the defaults here:

  * Column order is [x, y, t, p]  (NOT the [t,x,y,p] the spec listed as possible).
  * Polarity MUST be signed {-1, +1}. polarity_offset is 0.0, so a stored `0`
    negative event contributes nothing and is silently lost. ThinkCam records
    p in {0,1}, so we remap 0 -> -1 by default. This is the critical step.
  * Timestamps are compared directly against poses_ts; we keep microseconds
    (ThinkCam's confirmed unit, matching IncEventGS's TUM-VIE real data) and
    re-zero to the first event so float32 keeps integer-microsecond precision.

IMPORTANT (loader reality, see README note printed at the end): the released
ReplicaEventDataset / SimuEventDataset classes also require images + GT poses of
matching length (a hard assert). A pure event-only custom capture therefore needs
either real init poses/frames or a small custom dataset class. This converter can
emit a placeholder scaffold (--emit-scaffold) so the loader's asserts pass for a
smoke test, but a real reconstruction needs the loader question resolved first.
"""

import argparse
import json
import os
import sys

import numpy as np

try:
    import h5py
except ImportError:
    sys.exit("h5py is required: pip install h5py")


def _resolve_input(path):
    """Accept either an events.h5 file or a recording session directory."""
    if os.path.isdir(path):
        h5 = os.path.join(path, "events.h5")
        if not os.path.exists(h5):
            sys.exit(f"No events.h5 in session dir {path}")
        return h5, os.path.join(path, "metadata.json")
    return path, os.path.join(os.path.dirname(path), "metadata.json")


def load_events(h5_path):
    with h5py.File(h5_path, "r") as f:
        g = f["events"]
        x = g["x"][:]
        y = g["y"][:]
        t = g["t"][:]
        p = g["p"][:]
        width = int(g.attrs.get("width", 0))
        height = int(g.attrs.get("height", 0))
    n = len(x)
    if not (len(y) == len(t) == len(p) == n):
        sys.exit("Corrupt recording: x/y/t/p length mismatch.")
    return x, y, t.astype(np.float64), p, width, height


def remap_polarity(p, mode):
    """ThinkCam stores {0,1}. IncEventGS needs signed {-1,+1} (mode 'pm1')."""
    uniq = set(np.unique(p).tolist())
    if mode == "pm1":
        if not uniq <= {0, 1}:
            sys.exit(f"Expected source polarity in {{0,1}}, got {sorted(uniq)}")
        return (p.astype(np.int8) * 2 - 1).astype(np.float64)  # 0->-1, 1->+1
    if mode == "01":
        return p.astype(np.float64)
    sys.exit(f"Unknown polarity mode {mode}")


def build_event_array(x, y, t, p, col_order, dtype):
    cols = {"x": x.astype(np.float64), "y": y.astype(np.float64), "t": t, "p": p}
    order = ["x", "y", "t", "p"] if col_order == "xytp" else ["t", "x", "y", "p"]
    arr = np.stack([cols[c] for c in order], axis=1).astype(dtype)
    return arr, order


def validate(arr, order, width, height, polarity_mode):
    """Acceptance checks mirroring the plan's recorder/converter tests."""
    ti = order.index("t")
    xi, yi, pi = order.index("x"), order.index("y"), order.index("p")
    t = arr[:, ti]
    assert np.all(np.diff(t) >= 0), "timestamps not non-decreasing"
    assert arr[:, xi].max() < width and arr[:, xi].min() >= 0, "x out of [0,width)"
    assert arr[:, yi].max() < height and arr[:, yi].min() >= 0, "y out of [0,height)"
    pvals = set(np.unique(arr[:, pi]).tolist())
    expected = {-1.0, 1.0} if polarity_mode == "pm1" else {0.0, 1.0}
    assert pvals <= expected, f"polarity {pvals} not subset of {expected}"


def write_config_stub(out_dir, width, height, intr, threshold):
    fx, fy, cx, cy = intr
    calibrated = None not in (fx, fy, cx, cy)
    cx = cx if cx is not None else width / 2.0
    cy = cy if cy is not None else height / 2.0
    fx = fx if fx is not None else "FIXME_REQUIRES_CALIBRATION"
    fy = fy if fy is not None else "FIXME_REQUIRES_CALIBRATION"
    stub = f"""# IncEventGS run config stub generated by convert_to_inceventgs.py
# Edit datadir/output, then run: python main.py --config <this file>
# NOTE: dataset class below is a placeholder -- a pure event-only custom capture
# needs a custom dataset class (see converter output notes). Intrinsics live HERE,
# not in the dataset dir.
inherit_from: configs/SimuEvent/simu_event.yaml
dataset: 'replica_simu_event'   # placeholder; loader requires images+poses (see notes)
polarity_offset: 0.0            # converter already wrote signed {{-1,+1}} polarity

data:
  datadir: {os.path.abspath(out_dir)}
  scene: thinkcam_capture
  output: output/thinkcam_capture
  exp_name: demo
  downsample_factor: 1

cam:
  H: {height}
  W: {width}
  fx: {fx}
  fy: {fy}
  cx: {cx}
  cy: {cy}
  # calibrated: {calibrated}  (False => fx/fy are placeholders; calibrate the camera)

# event_threshold dir used: event_threshold_{threshold}
"""
    path = os.path.join(out_dir, "run_config_stub.yaml")
    with open(path, "w") as f:
        f.write(stub)
    return path, calibrated


def emit_scaffold(out_dir, knot_ts):
    """Placeholder images + identity traj so the stock loader's asserts pass.

    This is ONLY for exercising the dataloader as a smoke test. The identity
    poses are meaningless as ground truth -- they exist solely to satisfy
    len(poses_ts)==len(images)==len(traj). A real run needs the loader question
    resolved (real init poses/frames, or a custom event-only dataset class).
    """
    try:
        from PIL import Image
    except ImportError:
        sys.exit("--emit-scaffold needs Pillow: pip install pillow")
    img_dir = os.path.join(out_dir, "images")
    os.makedirs(img_dir, exist_ok=True)
    identity = "1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"
    with open(os.path.join(out_dir, "traj.txt"), "w") as f:
        for _ in knot_ts:
            f.write(identity + "\n")
    blank = Image.new("RGB", (32, 32), (0, 0, 0))
    for i in range(len(knot_ts)):
        blank.save(os.path.join(img_dir, f"frame{i:06d}.jpg"))
    return img_dir


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", required=True,
                    help="recordings/<session>/events.h5 or the session dir")
    ap.add_argument("--out", required=True, help="output dataset dir")
    ap.add_argument("--threshold", default="0.1",
                    help="contrast threshold C; sets event_threshold_<C>/ (default 0.1)")
    ap.add_argument("--col-order", choices=["xytp", "txyp"], default="xytp",
                    help="VERIFIED default: xytp (IncEventGS reads [:,2]=t,[:,0]=x,[:,1]=y,[:,3]=p)")
    ap.add_argument("--polarity", choices=["pm1", "01"], default="pm1",
                    help="VERIFIED default: pm1 (IncEventGS uses polarity_offset 0 -> needs signed)")
    ap.add_argument("--t-unit", choices=["us", "s"], default="us",
                    help="output time unit; source is microseconds (default us)")
    ap.add_argument("--dtype", choices=["float32", "float64"], default="float32",
                    help="loader casts to float32; default float32 to match their data")
    ap.add_argument("--no-rezero", action="store_true",
                    help="keep absolute timestamps instead of starting at 0")
    ap.add_argument("--pose-knots", type=int, default=100,
                    help="number of uniform time knots written to poses_ts.txt")
    ap.add_argument("--fx", type=float), ap.add_argument("--fy", type=float)
    ap.add_argument("--cx", type=float), ap.add_argument("--cy", type=float)
    ap.add_argument("--emit-scaffold", action="store_true",
                    help="also write placeholder images/+traj.txt so the stock loader runs (smoke test only)")
    args = ap.parse_args()

    h5_path, meta_path = _resolve_input(args.input)
    x, y, t, p, width, height = load_events(h5_path)

    meta = {}
    if os.path.exists(meta_path):
        with open(meta_path) as f:
            meta = json.load(f)
        if (not width or not height) and meta.get("resolution"):
            width, height = meta["resolution"]
    if not width or not height:
        sys.exit("Resolution unknown (not in H5 attrs or metadata.json).")

    # Re-zero + unit conversion (do this before float32 cast so precision is kept).
    if not args.no_rezero:
        t = t - t.min()
    if args.t_unit == "s":
        t = t / 1e6

    # float32 holds integers exactly only up to 2^24; warn if µs timestamps exceed it.
    if args.dtype == "float32" and args.t_unit == "us" and t.max() > 2 ** 24:
        secs = t.max() / 1e6
        print(f"WARNING: take is {secs:.1f}s; µs timestamps exceed float32 integer "
              f"precision (2^24≈16.7s). Use --t-unit s or --dtype float64.")

    p = remap_polarity(p, args.polarity)
    arr, order = build_event_array(x, y, t, p, args.col_order, np.dtype(args.dtype))

    # Raw captures can have rare out-of-order timestamps at buffer boundaries
    # (observed: one ~3ms reorder per ~4M-event take). IncEventGS compares t
    # directly and slices the stream by time, so guarantee monotonicity with a
    # stable sort (preserves order of equal-t events). No-op if already sorted.
    ti = order.index("t")
    if not np.all(np.diff(arr[:, ti]) >= 0):
        n_reorder = int((np.diff(arr[:, ti]) < 0).sum())
        arr = arr[np.argsort(arr[:, ti], kind="stable")]
        print(f"  sorted {n_reorder} out-of-order timestamp step(s) by t")

    validate(arr, order, width, height, args.polarity)

    # Write the one REQUIRED artifact.
    ev_dir = os.path.join(args.out, f"event_threshold_{args.threshold}")
    os.makedirs(ev_dir, exist_ok=True)
    npy_path = os.path.join(ev_dir, "gray_events_data.npy")
    np.save(npy_path, arr)

    # poses_ts.txt: uniform time knots spanning the event window (defines the
    # time-slicing for the trajectory; pose-free optimization fills in the rest).
    knot_ts = np.linspace(t.min(), t.max(), args.pose_knots)
    np.savetxt(os.path.join(args.out, "poses_ts.txt"), knot_ts, fmt="%.6f")

    intr = (args.fx, args.fy, args.cx, args.cy)
    if intr == (None, None, None, None) and meta.get("intrinsics"):
        m = meta["intrinsics"]
        intr = (m.get("fx"), m.get("fy"), m.get("cx"), m.get("cy"))
    cfg_path, calibrated = write_config_stub(args.out, width, height, intr, args.threshold)

    scaffold_dir = emit_scaffold(args.out, knot_ts) if args.emit_scaffold else None

    # ---- Report (print chosen conventions, as the plan requires) ----
    print(f"\n  Wrote {arr.shape[0]:,} events  -> {npy_path}")
    print(f"  array shape={arr.shape} dtype={arr.dtype} columns={order}")
    print(f"  polarity={args.polarity}  t_unit={args.t_unit}  rezero={not args.no_rezero}")
    print(f"  resolution={width}x{height}  t_span={t.max()-t.min():.1f} {args.t_unit}")
    print(f"  poses_ts.txt: {args.pose_knots} knots  ->  {os.path.join(args.out, 'poses_ts.txt')}")
    print(f"  config stub -> {cfg_path}")
    if not calibrated:
        print("  ⚠ intrinsics NOT calibrated: fx/fy are placeholders in the stub. "
              "Calibrate the camera and fill cam.fx/fy/cx/cy before a real run.")
    if scaffold_dir:
        print(f"  scaffold (smoke-test only): placeholder images/ + traj.txt written")
    print("\n  NOTE: IncEventGS's released ReplicaEventDataset/SimuEventDataset loaders "
          "assert len(poses_ts)==len(images)==len(traj). A pure event-only capture "
          "needs real init poses/frames OR a small custom dataset class. The .npy "
          "above is correct and final; the loader path is the remaining work.\n")


if __name__ == "__main__":
    main()
